spring:
  datasource:
    url: jdbc:h2:mem:zerowaste;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080 # Optional: Change the server port if needed

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method
    tagsSorter: alpha
